#########  this is for cmd 
# FROM ubuntu:latest
# CMD [ "echo", "this is from cmd docker file" ]
 
FROM ubuntu:latest
CMD [ "echo", "this is from cmd docker file" ]
ENTRYPOINT [ "echo", "this is from ENTRYPOINT" ]