#########  this is for cmd 
# FROM ubuntu:latest
# CMD [ "echo", "this is from cmd docker file" ]
 

 #########  this is for ENTRYPOINT and to check overide cmd
FROM ubuntu:latest
CMD [ "this is from cmd docker file" ]
ENTRYPOINT [ "echo", "this is from ENTRYPOINT" ]